### PR TITLE
Fixed flake8 errors

### PR DESCRIPTION
**Pull request by TechnologyClassroom**
I am making little PRs here and there for DigitalOcean's Hacktoberfest. I ran your script through flake8 and I was able to lower the number of hits. It is not passing 100%, but every little bit helps. These are the entries I was working on:

flake8:
E261 at least two spaces before inline comment
E302 expected 2 blank lines, found 1
E305 expected 2 blank lines after class or function definition, found 1
E401 multiple imports on one line
W293 blank line contains whitespace
W391 blank line at end of file

flake8 tic_tac_toe.py | wc -l               
18
user@gcg:~/builds/tic-tac-toe$ flake8 tic_tac_toe.py | wc -l
4

### CODE REVIEW

**Comment by zyocum** [comment]
Thanks!

I tried to checkout your patch, but apparently the patch is empty?

zyocum@mbp-zyocu-4925:~/Dropbox/Scripts/Python/tic-tac-toe[TechnologyClassroom-lint-changes|✓]$ curl -L https://github.com/zyocum/tic-tac-toe/pull/2.patch | git am -3             
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   142    0   142    0     0    654      0 --:--:-- --:--:-- --:--:--   654
100    32    0    32    0     0     64      0 --:--:-- --:--:-- --:--:--    64
Patch is empty.
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

Any idea what's up?

I'm going to make you a collaborator <https://github.com/zyocum/tic-tac-toe/invitations>, so you can create a branch and pull request directly via GitHub.

-Zach

**Comment by TechnologyClassroom** [comment]
I am not sure how you are viewing it, but it looks fine to me on github.

**Comment by zyocum** [comment]
The visual diff on GitHub looks fine, but I tried to checkout your patch locally and run your version (since I don't have any automated testing set up).

When I downloaded and tried to apply your patch with git am, it claims the patch is empty.

**Comment by TechnologyClassroom** [comment]
I had never heard of that method of viewing with .patch.  I have had a few instances of people continuing to develop their repo on my fork instead of their own so I have the habit of deleting my fork after a PR.  Maybe that is why github cannot show that way.

I figured out how to do it with git.

```
git clone https://github.com/zyocum/tic-tac-toe
cd tic-tac-toe
git fetch origin pull/2/head:PR
git checkout PR
vim tic-tac-toe.py
```

**Comment by zyocum** [comment]
@TechnologyClassroom , thanks that worked!

**Comment by TechnologyClassroom** [comment]
Once all of the linting errors are at zero, you can test with tox locally against multiple versions of python and numpy or link Travis for automated testing.  I have started teaching myself testing with my repo [dice-mechanic-sim](https://github.com/technologyclassroom/dice-mechanic-sim).  If you want to see tox in action locally, I built [a script](https://github.com/TechnologyClassroom/dice-mechanic-sim/blob/master/buildtoxtestenvironment.sh) to setup pyenv and tox that would work on any Debian based GNU/Linux distribution.

**Comment by zyocum** [comment]
I hadn't intended to do more work on this, so I didn't expect it to change very much at all (as such, automated testing seemed like overkill).

Tox is definitely something I've been meaning to learn, though.  Thanks for the resources!

**Comment by TechnologyClassroom** [comment]
tox is definitely overkill on this repo, but smaller projects are easier to learn a new concept with.

**Pull request merged**
